all:
	g++ main.cpp\
		socket/CSockConnector.h\
		socket/CSockConnector.cpp\
		socket/CSockAcceptor.h\
		socket/CSockAcceptor.cpp\
		socket/CSockStream.h\
		socket/CSockStream.cpp\
		socket/IIOStream.h\
		socket/IIOStream.cpp\
		socket/CInetAddr.h\
		socket/CInetAddr.cpp\
		-lpthread


